// <auto-generated />
using System;
using Harrbor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Harrbor.Data.Migrations
{
    [DbContext(typeof(HarrborDbContext))]
    partial class HarrborDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Harrbor.Data.Entities.TrackedRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArchivalStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CleanupCompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CleanupStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DownloadCompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("DownloadStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImportCompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastErrorAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("StagingPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TransferCompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TransferStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransferStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId")
                        .IsUnique();

                    b.HasIndex("DownloadStatus");

                    b.HasIndex("ImportStatus");

                    b.HasIndex("JobName");

                    b.HasIndex("TransferStatus");

                    b.ToTable("TrackedReleases");
                });
#pragma warning restore 612, 618
        }
    }
}
